//TNO,TESTNAME					, TEST FUNC
{ 1600, "DCM_SEQRM IDX CHECK"			, dcm_seqrm_idx_check},
{ 1610, "DCM_SEQRM BAR CHECK"			, dcm_seqrm_bar_check},
{ 1620, "DCM_SEQRM ISP CHECK"			, dcm_seqrm_isp_check},
{ 1630, "DCM_SEQRM CFLG CHECK"			, dcm_seqrm_cflg_check},
{ 1640, "DCM_SEQRM UBMAPLD1 CHECK"		, dcm_seqrm_ubmapld1_check},
{ 1650, "DCM_SEQRM AP CHECK"			, dcm_seqrm_ap_check},
{ 1660, "DCM_ADDRM CHECK"			, dcm_addrm_check},
{ 1670, "DCM_ADDRM AP CHECK"			, dcm_addrm_ap_check},
{ 1671, "DCM_ADDRM APSET(PAT) CHECK"		, dcm_addrm_apset_pat_check},
{ 1672, "DCM_ADDRM APSET(MAIN) CHECK"		, dcm_addrm_apset_main_check},
{ 1673, "DCM_ADDRM APINC CHECK"			, dcm_addrm_apinc_check},
{ 1680, "DCM_DATRM CHECK"			, dcm_datrm_check},
{ 1690, "DCM_DATRM AP CHECK"			, dcm_datrm_ap_check},
{ 1691, "DCM_DATRM APSET(PAT) CHECK"		, dcm_datrm_apset_pat_check},
{ 1692, "DCM_DATRM APSET(MAIN) CHECK"		, dcm_datrm_apset_main_check},
{ 1693, "DCM_DATRM APINC CHECK"	        	, dcm_datrm_apinc_check},
{ 1700, "DCM WAY CHECK"				, dcm_way_check},
