//TNO,TESTNAME									, TEST FUNC	,(TEST_drcparg) dr_vi, cp_vt, exphl
{  10, "FIXH LEVEL CHECK"						, TNO001	, {.drcparg={}}},
{  20, "FIXL LEVEL CHECK"						, TNO002	, {.drcparg={}}},
{  30, "OPEN CHECK"								, TNO003	, {.drcparg={}}},
{  40, "INH LEVEL CHECK"						, TNO004	, {.drcparg={}}},
{  50, "AND FAIL CHECK"							, andfail	, {.drcparg={}}},
{  60, "VT LEVEL CHECK"							, TNO005	, {.drcparg={}}},
{  70, "READ FCT CHECK (dousoku)"				, TNO007	, {.drcparg={}}},
{  80, "OUT LEVEL SCAN (dousoku)"				, TNO008	, {.drcparg={}}},
{  81, "OUT LEVEL SCAN (drcp) EXPL VI>VT"		, out_check	, {.drcparg={  2.3, -0.5, 0}}},
{  82, "OUT LEVEL SCAN (drcp) EXPL VI=VT"		, out_check	, {.drcparg={  1.0,  1.0, 0}}},
{  83, "OUT LEVEL SCAN (drcp) EXPL VI<VT"		, out_check	, {.drcparg={ -1.0,  2.0, 0}}},
{  84, "OUT LEVEL SCAN (drcp) EXPH VI>VT"		, out_check	, {.drcparg={  2.3, -0.5, 1}}},
{  85, "OUT LEVEL SCAN (drcp) EXPH VI=VT"		, out_check	, {.drcparg={  1.0,  1.0, 1}}},
{  86, "OUT LEVEL SCAN (drcp) EXPH VI<VT"		, out_check	, {.drcparg={ -1.0,  2.0, 1}}},
{  90, "SINGLE STRB TIMING SCAN (dousoku)"		, TNO009	, {.drcparg={}}},
{ 100, "DOUBLE STRB TIMING SCAN1 (dousoku)"		, TNO010	, {.drcparg={}}},
{ 110, "DOUBLE STRB TIMING SCAN2 (dousoku)"		, TNO011	, {.drcparg={}}},
{ 120, "LEVEL SET"								, TNO012	, {.drcparg={}}},
{ 130, "FIXED WAVEFORM OUTPUT LEVEL (DR)"		, TNO013	, {.drcparg={}}},
{ 140, "FIXED WAVEFORM OUTPUT LEVEL (DRE)"		, TNO014	, {.drcparg={}}},

