	{24000, "HardSync HangUp check(STPS)                      IOM2+6",outsync      ,{.fbgarg={patH,null,pc0  ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, expPASS_regcheck  }}},	//PASS
	{24001, "HardSync HangUp check(STFL)                      IOM2+6",outsync      ,{.fbgarg={patH,null,pc10 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, expFAIL_regcheck  }}},	//FAIL
	{24002, "HardSync HangUp check(FBGSYNC)                   IOM2+6",outsync      ,{.fbgarg={patH,null,pc20 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24003, "HardSync HangUp check(FBGSYNC Repeat)            IOM2+6",outsync      ,{.fbgarg={patH,null,pc30 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24004, "HardSync HangUp check(OFF-FBGSON)                IOM2+6",outsync      ,{.fbgarg={patH,null,pc40 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24005, "HardSync HangUp check(ON-FBGSON)                 IOM2+6",outsync      ,{.fbgarg={patH,null,pc40 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24006, "HardSync HangUp check(FBGSON  Repeat)            IOM2+6",outsync      ,{.fbgarg={patH,null,pc50 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24007, "HardSync HangUp check(OFF-FBGSOFF)               IOM2+6",outsync      ,{.fbgarg={patH,null,pc60 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24008, "HardSync HangUp check(ON-FBGSOFF)                IOM2+6",outsync      ,{.fbgarg={patH,null,pc60 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24009, "HardSync HangUp check(FBGSOFF Repeat)            IOM2+6",outsync      ,{.fbgarg={patH,null,pc70 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24010, "HardSync HangUp check(OFF-FBGSON/SYNC/OFF)       IOM2+6",outsync      ,{.fbgarg={patH,null,pc80 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24011, "HardSync HangUp check(OFF-FBGSON/SYNC/OFF Repeat)IOM2+6",outsync      ,{.fbgarg={patH,null,pc90 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24012, "HardSync HangUp check(MultiMeas On 100Repeat)    IOM2+6",outsync_multi,{.fbgarg={patH,null,pc90 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2, regcheck          }}},	//ALPG Stop chk+Reg chk
	{24013, "HardSync HangUp check(MpatSelector)              IOM2+6",outsync_sel  ,{.fbgarg={patM,null,pc100,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group_mpatsel,  grp2, regcheck  }}},	//ALPG Stop chk+Reg chk
	{24020, "HardSync HangUp check(STPS)                      IOM4+4",outsync      ,{.fbgarg={patH,null,pc0  ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, expPASS          }}},	//PASS
	{24021, "HardSync HangUp check(STFL)                      IOM4+4",outsync      ,{.fbgarg={patH,null,pc10 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, expFAIL          }}},	//FAIL
	{24022, "HardSync HangUp check(FBGSYNC)                   IOM4+4",outsync      ,{.fbgarg={patH,null,pc20 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24023, "HardSync HangUp check(FBGSYNC Repeat)            IOM4+4",outsync      ,{.fbgarg={patH,null,pc30 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24024, "HardSync HangUp check(OFF-FBGSON)                IOM4+4",outsync      ,{.fbgarg={patH,null,pc40 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24025, "HardSync HangUp check(ON-FBGSON)                 IOM4+4",outsync      ,{.fbgarg={patH,null,pc40 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24026, "HardSync HangUp check(FBGSON  Repeat)            IOM4+4",outsync      ,{.fbgarg={patH,null,pc50 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24027, "HardSync HangUp check(OFF-FBGSOFF)               IOM4+4",outsync      ,{.fbgarg={patH,null,pc60 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24028, "HardSync HangUp check(ON-FBGSOFF)                IOM4+4",outsync      ,{.fbgarg={patH,null,pc60 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24029, "HardSync HangUp check(FBGSOFF Repeat)            IOM4+4",outsync      ,{.fbgarg={patH,null,pc70 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24030, "HardSync HangUp check(OFF-FBGSON/SYNC/OFF)       IOM4+4",outsync      ,{.fbgarg={patH,null,pc80 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24031, "HardSync HangUp check(OFF-FBGSON/SYNC/OFF Repeat)IOM4+4",outsync      ,{.fbgarg={patH,null,pc90 ,8,FBGrate3,UT_OFF,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24032, "HardSync HangUp check(MultiMeas On 100Repeat)    IOM4+4",outsync_multi,{.fbgarg={patH,null,pc90 ,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group,  grp2b, regcheck         }}},	//ALPG Stop chk+Reg chk
	{24033, "HardSync HangUp check(MpatSelector)              IOM4+4",outsync_sel  ,{.fbgarg={patM,null,pc100,8,FBGrate3,UT_ON ,500e-9,meas_fct_per_group_mpatsel,  grp2b,regcheck  }}},	//ALPG Stop chk+Reg chk

	{24100, "HardSync(Pre) 1PG  check(CAL Adjust)" 	         	 ,common_pg    ,{.fbgarg={pat2,null,pc600,8,FBGrateM,UT_ON ,500e-9,shmoo_range_1pg   ,  grp2,  shmoo_check_teibai  }}},
	{24101, "HardSync Shmoo(PG1=PG2       )           IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc200,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_teibai  }}},
	{24102, "HardSync Shmoo(PG1>PG2 2400ns)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc300,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_teibai  }}},
	{24103, "HardSync Shmoo(PG1>PG2 2400ns)w/o teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc300,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check         }}},
	{24104, "HardSync Shmoo(PG1<PG2 2400ns)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc380,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_teibai  }}},
	{24105, "HardSync Shmoo(PG1<PG2 2400ns)w/o teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc380,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check         }}},
	{24106, "HardSync Shmoo(PG1=PG2       )           IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc200,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check_teibai  }}},
	{24107, "HardSync Shmoo(PG1>PG2 2400ns)w/  teibai IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc300,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check_teibai  }}},
	{24108, "HardSync Shmoo(PG1>PG2 2400ns)w/o teibai IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc300,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check         }}},
	{24109, "HardSync Shmoo(PG1<PG2 2400ns)w/  teibai IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc380,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check_teibai  }}},
	{24110, "HardSync Shmoo(PG1<PG2 2400ns)w/o teibai IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc380,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check         }}},
	{24111, "HardSync Shmoo Repeat(PG1<PG2)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc400,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_teibai  }}},
	{24112, "HardSync Shmoo Repeat(PG1<PG2)w/  teibai IOM4+4"        ,outsync      ,{.fbgarg={pat2,null,pc400,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check_teibai  }}},
	{24113, "HardSync Shmoo Selector(PG1<PG2)w/ teibai IOM2+6"       ,outsync_sel  ,{.fbgarg={patM,null,pc100,8,FBGrateM,UT_ON ,500e-9,shmoo_range_mpatsel,  grp2,  shmoo_check_teibai }}},
	{24114, "HardSync Shmoo Selector(PG1<PG2)w/ teibai IOM4+4"       ,outsync_sel  ,{.fbgarg={patM,null,pc100,8,FBGrateM,UT_ON ,500e-9,shmoo_range_mpatsel,  grp2b, shmoo_check_teibai }}},
	{24115, "HardSync Shmoo Repeat(PG1<>PG2)w/  teibai IOM2+6"       ,outsync      ,{.fbgarg={pat2,null,pc480,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_teibai  }}},
	{24116, "HardSync Shmoo Repeat(PG1<>PG2)w/o teibai IOM2+6"       ,outsync      ,{.fbgarg={pat2,null,pc480,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check         }}},
	{24117, "HardSync Shmoo Repeat(PG1<>PG2)w/  teibai IOM4+4"       ,outsync      ,{.fbgarg={pat2,null,pc480,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check_teibai  }}},
	{24118, "HardSync Shmoo Repeat(PG1<>PG2)w/o teibai IOM4+4"       ,outsync      ,{.fbgarg={pat2,null,pc480,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2b, shmoo_check         }}},
	{24119, "HardSync Shmoo*Match     w/  teibai IOM4+4"             ,outsync_match,{.fbgarg={pat2,null,pc550,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2b, match_shmoo_check_teibai}}},
	{24120, "HardSync Shmoo*Match     w/  teibai IOM2+6"             ,outsync_match,{.fbgarg={pat2,null,pc550,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  match_shmoo_check_teibai}}},
	{24121, "HardSync Shmoo+OUT   (PG1<PG2)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc700,8,FBGrateM,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_allpass }}},	//pc400 + OUT(change vih/vil or voh/vol in pattern)	//ALL PASS exp
	{24122, "HardSync Shmoo+CALM  (PG1<PG2)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc800,8,FBGrateM,UT_ON ,500e-9,shmoo_range_CALM  ,  grp2,  shmoo_check_allpass }}},	//pc400 + CALM(change vih/vil or voh/vol in main)	//ALL PASS exp
	{24123, "HardSync Shmoo+WAIT  (PG1<PG2)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pc900,8,FBGrateM,UT_ON ,500e-9,shmoo_range_CALM  ,  grp2,  shmoo_check_allpass }}},	//pc400 + WAIT(change vih/vil or voh/vol in main)	//ALL PASS exp
	{24124, "HardSync Shmoo+JBF   (PG1<PG2)w/  teibai IOM2+6"        ,outsync      ,{.fbgarg={pat2,null,pcA00,8,FBGrateM,UT_ON ,500e-9,shmoo_range_DBM   ,  grp2,  shmoo_check_allfail }}},	//pc400 + JBF(Wait DBM xfer to meet with dbm)
	{24200, "HardSync Shmoo Single 8Group"                           ,outsync_8grp ,{.fbgarg={pat8,null,pc500,8,FBGrateM,UT_ON ,500e-9,shmoo_range         ,  grp8, shmoo_check_teibai }}},	//in drcp spec
	{24201, "HardSync Shmoo*Rejection(DUT3) w/o teibai IOM2+6"       ,outsync_rej_3,{.fbgarg={pat2,null,pc300,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_reject  }}},
	{24202, "HardSync Shmoo*Rejection(DUT1) w/o teibai IOM2+6"       ,outsync_rej_1,{.fbgarg={pat2,null,pc300,8,FBGrate ,UT_ON ,500e-9,shmoo_range       ,  grp2,  shmoo_check_reject  }}},

